# Generated by Django 2.2.5 on 2019-09-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('measuring_system', models.CharField(max_length=32, verbose_name='Единцы измерения')),
                ('provider', models.CharField(max_length=32, verbose_name='Поставщик')),
            ],
        ),
    ]
