# Generated by Django 2.2.5 on 2019-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('unit', models.IntegerField(choices=[(0, 'шт.'), (1, 'кг.')], default=0, verbose_name='Unit')),
                ('provider', models.CharField(blank=True, max_length=128, verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
